pipeline {
  agent any

  environment {
    APP_NAME = "sample-app"
    TOMCAT_HOST = "54.226.249.129"   // replace with your server IP
    TOMCAT_USER = "ubuntu"           // your EC2 login user
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/Sangamesh24/Tomcat_deploy.git', branch: 'main'
      }
    }

    stage('Build WAR') {
    steps {
        dir('sample-app') {   // Go inside project folder
            sh 'mvn clean package -DskipTests'
        }
    }
}
    
    stage('Copy WAR to Tomcat server') {
      steps {
        sshagent(credentials: ['key-ubuntu']) {
          sh '''
            echo "Copying WAR to Tomcat server..."
            scp -o StrictHostKeyChecking=no target/*.war ${TOMCAT_USER}@${TOMCAT_HOST}:/opt/tomcat/webapps/${APP_NAME}.war
          '''
        }
      }
    }

    stage('Restart Tomcat') {
      steps {
        sshagent(credentials: ['key-ubuntu']) {
          sh '''
            echo "Restarting Tomcat..."
            ssh -o StrictHostKeyChecking=no ${TOMCAT_USER}@${TOMCAT_HOST} "sudo systemctl restart tomcat"
          '''
        }
      }
    }
  }

  post {
    success {
      echo "✅ Deployment Successful!"
    }
    failure {
      echo "❌ Deployment Failed!"
    }
  }
}
